name: churn-imbalanced-dvc-pipline

on: [push]

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: iterative/setup-cml@v1

      - name: prepare environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro
          git fetch --prune
          echo "## Metrics" > report.md
          dvc metrics diff --md main >> report.md

          echo "## Confusion Matrix" >> report.md
          echo "![](./conf_matrix.png)" >> report.md

          cml comment create report.md
